// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVSXMxkpbQkRfu_aHO1ruoB79MZiqQv0E',
    appId: '1:421065125327:web:4bd21107c1217dbef776ba',
    messagingSenderId: '421065125327',
    projectId: 'doc-sense-1b4b9',
    authDomain: 'doc-sense-1b4b9.firebaseapp.com',
    storageBucket: 'doc-sense-1b4b9.firebasestorage.app',
    measurementId: 'G-XBC7SQZ5WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCy7JkAC_pC1yLuBb4q332wMEkOwHrrI',
    appId: '1:421065125327:android:cc5a3b44d889d638f776ba',
    messagingSenderId: '421065125327',
    projectId: 'doc-sense-1b4b9',
    storageBucket: 'doc-sense-1b4b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5GlO4QVmhNFNMNrQzTJGXrWFw1ZegNo',
    appId: '1:421065125327:ios:381c688adae0c452f776ba',
    messagingSenderId: '421065125327',
    projectId: 'doc-sense-1b4b9',
    storageBucket: 'doc-sense-1b4b9.firebasestorage.app',
    iosBundleId: 'com.example.docSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5GlO4QVmhNFNMNrQzTJGXrWFw1ZegNo',
    appId: '1:421065125327:ios:381c688adae0c452f776ba',
    messagingSenderId: '421065125327',
    projectId: 'doc-sense-1b4b9',
    storageBucket: 'doc-sense-1b4b9.firebasestorage.app',
    iosBundleId: 'com.example.docSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVSXMxkpbQkRfu_aHO1ruoB79MZiqQv0E',
    appId: '1:421065125327:web:7edeb48bbed657fcf776ba',
    messagingSenderId: '421065125327',
    projectId: 'doc-sense-1b4b9',
    authDomain: 'doc-sense-1b4b9.firebaseapp.com',
    storageBucket: 'doc-sense-1b4b9.firebasestorage.app',
    measurementId: 'G-QW1VHMJ1WP',
  );
}
